#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python manage.py makemigrations
echo "makemigrations done"
python manage.py migrate
echo "migrate done"
python manage.py runserver_plus 0.0.0.0:8000
